WriteLux-main/fitness/urls.py
from django.urls import path
from . import views

app_name = 'fitness'

urlpatterns = [
    path('', views.fitness_items, name='fitness_items'),
    path('search/', views.search, name='search'),  # Add this line
    path('lesson/<slug:param>/', views.lesson_page, name='lesson_page'),
    path('course/<slug:param>/', views.course_page, name='course_page'),
]

WriteLux-main/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    #path("", views.posts_list, name='list'),
    #path("new_post/", views.new_post, name='new_post'),
    #path('<slug:param>', views.post_page, name='post_page'),
    #path('post/<int:pk>/delete/', views.PostDeleteView.as_view(), name='post_delete'), # added delete task

    path('', views.posts_list, name='posts_list'),
    path('search/', views.search, name='search'),  # Add this line
    path('dashboard/', views.post_list, name='post_list'),
    path("new_post/", views.new_post, name='new_post'),
    path('create/', views.post_create, name='post_create'),
    path('<slug:param>/', views.post_page, name='post_page'),
    path('update/<int:pk>/', views.post_update, name='post_update'),
    path('delete/<int:pk>/', views.post_delete, name='post_delete'),
]

WriteLux-main/users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.login_user, name='login_user'),
    path('logout/', views.logout_user, name='logout_user'),
]

fitness/urls.py
from django.urls import path
from . import views

app_name = 'fitness'

urlpatterns = [
    path('', views.fitness_home, name='fitness_home'),
    path('search/', views.search, name='search'),  # Add this line
    path('lesson/<slug:param>/', views.lesson_page, name='lesson_page'),
    path('course/<slug:param>/', views.course_page, name='course_page'),

    # Add more paths as needed, e.g., for article detail pages
    path('article/<int:id>/', views.article_detail, name='article_detail'),
]

myproject/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf.urls.static import static
from django.conf import settings
from .views import PostCreateView, PostDetailView, PostUpdateView, PostDeleteView, generate_portfolio_url

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", views.home, name='home'), 
    path('search/', views.search, name='search'),
    path("dashboard/", views.dashboard, name='dashboard'),
    path("image/", views.image_list, name='image'),
    path('generate-portfolio-url/', generate_portfolio_url, name='generate_portfolio_url'),
    path('faq/', views.faq, name='faq'),
    
    path("posts/", include('posts.urls')),  # Include the URLs from the posts app
    path('fitness/', include('fitness.urls')),  # Include the URLs from the fitness app
    path('users/', include('users.urls')),  # Include the URLs from the users app
    path('tinymce/', include('tinymce.urls')),
    path('accounts/', include('allauth.urls')),  # Include allauth URLs
    path('swiper_example/', views.swiper_example, name='swiper_example'),

    path('dashboard/post/new/', PostCreateView.as_view(), name='post_create'),
    path('dashboard/post/<int:pk>/', PostDetailView.as_view(), name='post_detail'),
    path('dashboard/post/<int:pk>/edit/', PostUpdateView.as_view(), name='post_update'),
    path('dashboard/post/<int:pk>/delete/', PostDeleteView.as_view(), name='post_delete'),

    path('accounts/', include('allauth.urls')),  # Include allauth URLs

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from . import views
from .views import PostUpdateView, PostDetailView, PostCreateView, PostDeleteView

app_name = 'posts'

urlpatterns = [
    path('', views.posts_list, name='posts_list'),
     path('contact/', views.contact, name='contact'),
    path('newsletter_signup/', views.newsletter_signup, name='newsletter_signup'),
    path('search/', views.search, name='search'),
    path('dashboard/', views.post_list, name='post_list'),
    path('new_post/', views.new_post, name='new_post'),
    path('<slug:param>/', views.post_page, name='post_page'),
    
    # Class-based view URLs
    path('post/<int:pk>/update/', PostUpdateView.as_view(), name='post_update'),
    path('post/<int:pk>/', PostDetailView.as_view(), name='post_detail'),
    path('post/new/', PostCreateView.as_view(), name='post_create'),
    path('post/<int:pk>/delete/', PostDeleteView.as_view(), name='post_delete'),
]

WriteLux-main/posts/forms.py
from django import forms
from tinymce.widgets import TinyMCE
from . import models

class CustomForm(forms.ModelForm):
    body = forms.CharField(widget=TinyMCE(attrs={'cols': 80, 'rows': 30}))
    
    class Meta:
        model = models.Post
        fields = ("title", "body", "slug", "banner") # Adjust fields as needed

WriteLux-main/users/forms.py
# users/forms.py

from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django import forms
from .email_utils import send_registration_confirmation_email  # Import the utility function

class CustomUserCreationForm(UserCreationForm):
    email = forms.EmailField(required=True, help_text='', label='Email Address',
                             widget=forms.EmailInput(attrs={'class': 'custom-class'}))

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

    def __init__(self, *args, **kwargs):
        super(CustomUserCreationForm, self).__init__(*args, **kwargs)
        self.fields['username'].help_text = ''
        self.fields['password1'].widget.attrs.update({'class': 'custom-class'})
        self.fields['password2'].widget.attrs.update({'class': 'custom-class'})
        self.fields['password1'].help_text = ''
        self.fields['password2'].help_text = ''

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError("This email address is already in use.")
        return email

    def save(self, commit=True):
        user = super(CustomUserCreationForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        if commit:
            user.save()
            print("User saved, sending email...")
            send_registration_confirmation_email(user)  # Send the confirmation email
            print("Email function called.")
        return user

WriteLux-main/fitness/views.py
from django.shortcuts import render, get_object_or_404
from .models import Fitness, Image, Lesson, Course, Home
from posts.models import Post

def fitness_items(request):
    fitness = Fitness.objects.all()
    return render(request, 'fitness/fitness_items.html', {'fitness': fitness})

def search(request):
    query = request.GET.get('q')
    if query:
        fitness_results = Fitness.objects.filter(name__icontains=query)
        lesson_results = Lesson.objects.filter(name__icontains=query)
        course_results = Course.objects.filter(title__icontains=query)
        post_results = Post.objects.filter(title__icontains=query)
        home_results = Home.objects.filter(title__icontains=query)
    else:
        fitness_results = Fitness.objects.none()
        lesson_results = Lesson.objects.none()
        course_results = Course.objects.none()
        post_results = Post.objects.none()
        home_results = Home.objects.none()

    context = {
        'query': query,
        'fitness': fitness_results,
        'lessons': lesson_results,
        'courses': course_results,
        'posts': post_results,
        'home': home_results
    }
    return render(request, 'fitness/search_results.html', context)

def lesson_page(request, param):
    posts = Post.objects.all()
    lessons = Lesson.objects.all()
    courses = Course.objects.all()
    lesson = get_object_or_404(Lesson, slug=param)
    context = {
        'posts': posts,
        'lessons': lessons,
        'courses': courses,
        'lesson': lesson
    }
    return render(request, 'fitness/lesson_page.html', context)

def course_page(request, param):
    posts = Post.objects.all()
    courses = Course.objects.all()
    lessons = Lesson.objects.all()
    course = get_object_or_404(Course, slug=param)
    context = {
        'posts': posts,
        'courses': courses,
        'lessons': lessons,
        'course': course
    }
    return render(request, 'fitness/course_page.html', context)

WriteLux-main/myproject/views.py
from django.shortcuts import render, get_object_or_404, redirect
from fitness.models import Image
from posts.models import Post
from fitness.models import Lesson, Course, Fitness, Home
from django.contrib.auth.decorators import login_required
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, DetailView
from django.urls import reverse_lazy
from posts.forms import CustomForm
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib import messages

def home(request):
    courses = Course.objects.all()
    posts = Post.objects.all()
    lessons = Lesson.objects.all()
    home_content = Home.objects.all()
    context = {
        'courses': courses,
        'posts': posts,
        'lessons': lessons,
        'home_content': home_content
    }
    return render(request, 'home.html', context)

def search(request):
    query = request.GET.get('q')
    if query:
        fitness_results = Fitness.objects.filter(name__icontains=query)
        lesson_results = Lesson.objects.filter(name__icontains=query)
        course_results = Course.objects.filter(title__icontains=query)
        post_results = Post.objects.filter(title__icontains=query)
    else:
        fitness_results = Fitness.objects.none()
        lesson_results = Lesson.objects.none()
        course_results = Course.objects.none()
        post_results = Post.objects.none()

    context = {
        'query': query,
        'fitness': fitness_results,
        'lessons': lesson_results,
        'courses': course_results,
        'posts': post_results
    }
    return render(request, 'search_results.html', context)

@login_required(login_url="/users/login/")
def dashboard(request):
    user = request.user
    posts = Post.objects.filter(author=user)
    context = {
        'user': user,
        'posts': posts,
    }
    return render(request, 'dashboard.html', context)

def image_list(request):
    posts = Post.objects.all()
    images = Image.objects.all()
    context = {
        'images': images,
        'posts': posts
    }
    return render(request, 'image_list.html', context)

def image_logo(request):
    logo = Image.objects.all()[0]
    return render(request, 'layout.html', {'logo': logo})

def contact(request):
    post_contact = Post.objects.all()
    return render(request, 'contact.html', {'post_contact': post_contact})

class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    form_class = CustomForm
    template_name = 'posts/post_form.html'
    success_url = reverse_lazy('dashboard')

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)
    
class PostDetailView(DetailView):
    model = Post
    template_name = 'posts/post_detail.html'
    context_object_name = 'post'

class PostUpdateView(UpdateView):
    model = Post
    form_class = CustomForm
    template_name = 'posts/post_form.html'
    success_url = reverse_lazy('dashboard')

    def form_valid(self, form):
        messages.success(self.request, 'Your post was successfully updated!')
        return super().form_valid(form)

    def get_queryset(self):
        return Post.objects.filter(author=self.request.user)

class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Post
    template_name = 'posts/post_confirm_delete.html'
    success_url = reverse_lazy('dashboard')

    def test_func(self):
        post = self.get_object()
        return self.request.user == post.author

WriteLux-main/posts/views.py
from django.shortcuts import render, get_object_or_404, redirect

# 5-07-24
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.urls import reverse_lazy
from django.views.generic.edit import DeleteView
# added above delete task

from .models import Post
from fitness.models import Lesson, Course, Fitness
from django.contrib.auth.decorators import login_required
from . import forms

from .forms import CustomForm
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, DetailView

# Create your views here.

def search(request):
    query = request.GET.get('q')
    if query:
        fitness_results = Fitness.objects.filter(name__icontains=query)
        lesson_results = Lesson.objects.filter(name__icontains=query)
        course_results = Course.objects.filter(title__icontains=query)
        post_results = Post.objects.filter(title__icontains=query)
    else:
        fitness_results = Fitness.objects.none()
        lesson_results = Lesson.objects.none()
        course_results = Course.objects.none()
        post_results = Post.objects.none()

    context = {
        'query': query,
        'fitness': fitness_results,
        'lessons': lesson_results,
        'courses': course_results,
        'posts': post_results
    }
    return render(request, 'posts/search_results.html', context)

def posts_list(request):
    # function created posts_list
    posts = Post.objects.all().order_by('-date')
    courses = Course.objects.all()
    lessons = Lesson.objects.all() # Fetch all lessons from the lesson model in the fitness app
    context = {
        'posts': posts,
        'lessons': lessons,
        'courses': courses
    }
    return render(request, 'posts/posts_list.html', context)

def post_page(request, param):
    post = Post.objects.get(slug=param)
    courses = Course.objects.all()
    lessons = Lesson.objects.all() # Fetch all lessons from the lesson model in the fitness app
    context = {
        'post': post,
        'lessons': lessons,
        'courses': courses
    }
    return render(request, 'posts/post_page.html', context) 

@login_required(login_url="/users/login/")
def new_post(request):
    if request.method == 'POST':
        form = forms.CustomForm(request.POST, request.FILES)
        if form.is_valid():
            newForm = form.save(commit=False)
            newForm.author = request.user
            newForm.save()
            return redirect('posts:post_list')
    else:
        form = forms.CustomForm()
    return render(request, 'posts/new_post.html', {'form': form})

# 05-07-24
class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Post
    success_url = reverse_lazy('posts:list')  # Redirect to the list of posts after deletion
    template_name = 'posts/post_confirm_delete.html'

    def test_func(self):
        post = self.get_object()
        return self.request.user == post.author

    def handle_no_permission(self):
        if self.request.user.is_authenticated:
            return super().handle_no_permission()
        return redirect(self.request.get_full_path())
# done and ok

class PostListView(ListView):
    model = Post
    template_name = 'posts/posts_list.html'
    context_object_name = 'posts'

class PostCreateView(CreateView):
    model = Post
    form_class = CustomForm
    template_name = 'posts/post_form.html'
    success_url = reverse_lazy('posts:post_list')

class PostUpdateView(UpdateView):
    model = Post
    form_class = CustomForm
    template_name = 'posts/post_form.html'
    success_url = reverse_lazy('posts:post_list')

class PostDeleteView(DeleteView):
    model = Post
    template_name = 'posts/post_confirm_delete.html'
    success_url = reverse_lazy('posts:post_list')

class PostDetailView(DetailView):
    model = Post
    template_name = 'posts/post_detail.html'
    context_object_name = 'post'

post_list = PostListView.as_view()
post_create = PostCreateView.as_view()
post_update = PostUpdateView.as_view()
post_delete = PostDeleteView.as_view()
post_detail = PostDetailView.as_view()

WriteLux-main/users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from .forms import CustomUserCreationForm
from django.contrib.auth import login, logout
#from django.contrib.auth.decorators import login_required

def register(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('users:login_user')  # Adjust redirect as necessary
    else:
        form = CustomUserCreationForm()
    return render(request, 'users/register.html', {'form': form})

def login_user(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            # Login 
            user = form.get_user()
            login(request, user)
            return redirect('dashboard')
    else:
        form = AuthenticationForm()
    return render(request, 'users/login.html', {'form': form})

def logout_user(request):
    if request.method == 'POST' or request.method == 'GET': 
        logout(request)
        return redirect('home')

WriteLux-main/templates/home.html
{% extends "layout.html" %}
{% block content %}
    <img 
    class="home-image"
    src="/media/Blog-Cover-Photos-6.png" alt="Blog image 6"  arial-label="Blog home image" title="Blog homw image"
    >
    {% for blog in home_content %}
        <section>
            <p>{{ blog.body|safe }}</p>
        </section>
    {% endfor %}
    <p>Check out the <a href="/users/registration">User Dashboard</a> page</p>
{% endblock  %}

{% block content1 %}
    <!-- Search form -->
    <form action="{% url 'search' %}" method="get">
        <input type="text" name="q" placeholder="Search...">
        <button type="submit">Search</button>
    </form>
    <section>
        {% for course in courses %} <!-- courses = Course.objects.all() {'courses': courses} in views.py -->
            <article>
                <!-- app_name = 'fitness' -->
                <a href="{% url 'fitness:course_page' param=course.slug %}">{{ course.title }}</a>
                <!-- 'posts:post_page' This means the function post_page in views.py in the app posts -->
            </article>
        {% endfor %}
    </section>
    <div class="slider-container">
        <div class="slider content1-slider">
            <img src="/media/Blog-Cover-Photos-6.png" alt="Blog image 1" arial-label="Blog image" title="Blog image">
            <img src="/media/Blog-Cover-Photos-2.png" alt="Blog image 2" arial-label="Blog image" title="Blog image">
            <img src="/media/images/Blog-Cover-Photos-3.png" alt="Blog image 3" arial-label="Blog image" title="Blog image">
            <img src="/media/Blog-Cover-Photos-4.jpg" alt="Blog image 4" arial-label="Blog image" title="Blog image">
            <img src="/media/Blog-Cover-Photos-1.jpg" alt="Blog image 5" arial-label="Blog image" title="Blog image">
        </div>
    </div>
{% endblock  %}

{% block content2 %}
    <h1 class="text-animation-home-content2">Busness Plan</h1>
    <section>
        {% for lesson in lessons %}
            <article>
                <!-- app_name = 'fitness' -->
                <a href="{% url 'fitness:lesson_page' param=lesson.slug %}">{{ lesson.name }}</a>
                <!-- 'fitness:lesson_page' This means the function lesson_page in views.py in the app fitness -->
            </article>
        {% endfor %}
    </section>
    <div class="slider-container">
        <div class="slider">
            <img src="/media/Blog-Cover-Photos-1.jpg" alt="Blog image 1" arial-label="Blog image" title="Blog image">
            <img src="/media/Blog-Cover-Photos-4.jpg" alt="Blog image 4" arial-label="Blog image" title="Blog image">
            <img src="/media/Blog-Cover-Photos-2.png" alt="Blog image 2" arial-label="Blog image" title="Blog image">
            <img src="/media/Blog-Cover-Photos-5.png" alt="Blog image 5" arial-label="Blog image" title="Blog image">
            <img src="/media/Blog-Cover-Photos-3.png" alt="Blog image 3" arial-label="Blog image" title="Blog image">
        </div>
    </div> 
{% endblock  %}
    

WriteLux-main/templates/image_list.html
{% extends "layout.html" %}

{% block title %}
    service 
{% endblock  %}

{% block content %}
    <section>
        <h1>Available Images</h1>
        
            {% for image in images %}
                <img 
                    class="image-gallery"
                    src="{{ image.image.url }}" alt="{{ image.title }}"
                />
            {% endfor %}
    </section>
    <p>check the logo <a href="{% url "image-logo" %}">click</a></p>
{% endblock  %}

<!-- add the grid container for content1 and content2 -->
{% block content1 %}
<h1>WriteLux Images</h1>
<section>
    {% for post in posts %} 
        <img 
            class="banner-images-content1"
            src="{{ post.banner.url }}" alt="{{ post.title }}" 
        />
    {% endfor %}
    <p>Back to <a href="{% url 'posts:posts_list' %}">WriteLux</a></p>
</section>
{% endblock  %}

{% block content2 %}
<h1>WriteLux Images</h1>
<section>
    {% for post in posts %} 
    <img 
        class="banner-images-content2"
        src="{{ post.banner.url }}" alt="{{ post.title }}" 
    />
    {% endfor %}
    <p>Back to <a href="{% url 'posts:posts_list' %}">WriteLux</a></p>
</section>
{% endblock  %}

WriteLux-main/templates/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- STYLE SHEETS -->
    
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css"
    />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css"
      integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA=="
      crossorigin="anonymous"
      referrerpolicy="no-referrer"
    />

    <!-- BOOTSTRAP -->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN"
      crossorigin="anonymous"
    />
    <link rel="stylesheet" href="{% static 'css-style/layout.css' %}">
    <link rel="stylesheet" href="{% static 'css-style/style.css' %}">

    <script src="{% static 'js/main.js' %}" defer></script>
    {% block extra_scripts %}

    {% endblock %}
</head>
<body>
    <nav class="navbar navbar-expand-lg fixed-top">
        <div class="container-fluid">
            <button
            type="button"
            data-bs-toggle="collapse"
            data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent"
            aria-expanded="false"
            aria-label="Toggle navigation"
            class="navbar-toggler navbar-toggler-right"
            >
            <i class="fa fa-bars"></i>
            </button>
            <div id="navbarSupportedContent" class="collapse navbar-collapse">
                <ul class="navbar-nav ml-auto">
                  <li class="nav-item">
                    <a
                      class="nav-link active home"
                      aria-current="page"
                      href="{% url 'posts:posts_list' %}"
                      >WRITELUX</a
                    >
                </li>
                <li class="nav-item dropdown">
                  <a
                    class="nav-link dropdown-toggle"
                    href="{% url 'fitness:fitness_items' %}"
                    role="button"
                    data-bs-toggle="dropdown"
                    aria-expanded="false"
                  >
                    More
                  </a>
                  <ul class="dropdown-menu">
                    <li>
                      <a class="dropdown-item" href="#"> FAQS</a>
                    </li>
                    <li><a class="dropdown-item" href="#">Whats New</a></li>
                    <li><a class="dropdown-item" href="#">Contact Us</a></li>
                  </ul>
                </li>
                <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle no_arrow" href="{% url 'users:register' %}"><span role="img" aria-label="User Registration" title="User Registration">Registration</span></a>
                </li>
                {% if user.is_authenticated %} 
                <li class="nav-item dropdown">
                  <a
                    class="nav-link dropdown-toggle no_arrow"
                    href="{% url 'dashboard' %}"
                    role="button"
                    data-bs-toggle="dropdown"
                    aria-expanded="false"
                  >
                    Dashboard
                  </a>
                </li>
                <li class="nav-item dropdown">
                  <a
                    class="nav-link dropdown-toggle no_arrow"
                    href="{% url 'image' %}"
                    role="button"
                    data-bs-toggle="dropdown"
                    aria-expanded="false"
                  >
                    images
                  </a>
                </li>
                <li class="nav-item dropdown">
                    <div class="write">
                      <a
                        class="nav-link dropdown-toggle no_arrow"
                        href="{% url 'posts:new_post' %}"
                        role="button"
                        data-bs-toggle="dropdown"
                        aria-expanded="false"
                      >
                    NEW POST
                      </a>
                    </div>
                </li>
                <form class="logout" action="{% url 'users:logout_user' %}" method='POST'>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:logout_user' %}"
                      ><button class="btn text-light me-1" type="button">
                        LOGOUT
                      </button></a
                    >
                </li>
                </ul>
              </form>
              </div>
            </div>
        <!-- {% else %}

        <form class="login" action="{% url 'users:login_user' %}">
            {% csrf_token %}
            <button class="login-button" aria-label="user login" title="user login">Login</button>
        </form>  
    
        {% endif %}  -->

    </nav>


    <div class="grid-container">
        <aside class="sidebar">
            <div class="content1">
                {% block content1 %}
                
                {% endblock %}
            </div>

            <div class="content1A">
                {% block content1A %}
                
                {% endblock %}
            </div>

        </aside>
        <main>
            {% if messages %}
                <ul class="messages">
                    {% for message in messages %}
                        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                    {% endfor %}
                </ul>
            {% endif %}
            {% block content %}
            
            {% endblock %}
        </main>
        <aside class="sidebar">
            {% block content2 %}
            
            {% endblock %}
        </aside>
    </div>
    <footer>
        <p>&copy; 2024 WriteLux. All rights reserved.</p>
    </footer>

<script
    src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
    crossorigin="anonymous"
></script>
<script
    src="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/js/bootstrap.min.js"
    integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
    crossorigin="anonymous"
></script>
</body>
</html>

WriteLux-main/templates/logo.html
{% extends "layout.html" %}

{% block title %}
    logo 
{% endblock  %}

{% block content %}
    <h1>Logo Image</h1>
        <img src="{{ logo.image.url }}" alt="{{ image.title }}" width="150">
{% endblock  %}

WriteLux-main/templates/search_results.html
{% extends "layout.html" %}

{% block title %}
    Search Results
{% endblock %}

{% block content %}
    <section>
        <h1>Search Results for "{{ query }}"</h1>

        {% if fitness %}
            <h2>Fitness</h2>
            <ul>
                {% for item in fitness %}
                    <li>{{ item.name }}</li>
                {% endfor %}
            </ul>
        {% endif %}

        {% if lessons %}
            <h2>Lessons</h2>
            <ul>
                {% for lesson in lessons %}
                    <li><a href="{% url 'fitness:lesson_page' param=lesson.slug %}">{{ lesson.name }}</a></li>
                {% endfor %}
            </ul>
        {% endif %}

        {% if courses %}
            <h2>Courses</h2>
            <ul>
                {% for course in courses %}
                    <li><a href="{% url 'fitness:course_page' param=course.slug %}">{{ course.title }}</a></li>
                {% endfor %}
            </ul>
        {% endif %}

        {% if posts %}
            <h2>Posts</h2>
            <ul>
                {% for post in posts %}
                    <li><a href="{% url 'posts:post_page' param=post.slug %}">{{ post.title }}</a></li>
                {% endfor %}
            </ul>
        {% endif %}

        {% if not fitness and not lessons and not courses and not posts %}
            <p>No results found</p>
        {% endif %}
    </section>
    <p>Back to <a href="{% url 'home' %}">Home</a></p>
{% endblock %}

{% block content1 %}
    <h2><a href="/">Contents</a></h2>
    <p>Contents Area</p>
{% endblock %}

{% block content2 %}
    <h2><a href="/">Business</a> Plan</h2>
    <p>Business Area</p>
{% endblock %}